steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['install', './tronimoes_server']
  env: ['PROJECT_ROOT=github.com/skelterjohn/tronimoes']
  dir: 'server'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--file=Dockerfile.server', '--tag=gcr.io/$PROJECT_ID/server:v$SHORT_SHA', '.']
  dir: 'server'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/server:v$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: 
  - '-q'
  - 'run'
  - 'deploy'
  - '--image=gcr.io/$PROJECT_ID/server:v$SHORT_SHA'
  - '--platform=managed'
  - '--region=us-east4'
  - '--set-env-vars=SHORT_SHA=$SHORT_SHA'
  - '--set-env-vars=DB_HOST=172.30.32.3'
  - '--set-env-vars=DB_NAME=conductor'
  - '--allow-unauthenticated'
  - '--revision-suffix=v$SHORT_SHA'
  - 'autopush'
images:
- 'gcr.io/$PROJECT_ID/server:v$SHORT_SHA'
options:
  requestedVerifyOption: VERIFIED
