package game

import "errors"

var (
	ErrGameAlreadyStarted       = errors.New("game already started")
	ErrGameTooManyPlayers       = errors.New("game already has 6 players")
	ErrGameNotEnoughPlayers     = errors.New("not enough players")
	ErrGamePreviousRoundNotDone = errors.New("previous round not done")
	ErrPlayerAlreadyInGame      = errors.New("player already in game")
	ErrRoundAlreadyDone         = errors.New("round already done")
	ErrRoundNotStarted          = errors.New("round not started")
	ErrNotYourTurn              = errors.New("not your turn")
	ErrNotYourGame              = errors.New("not your game")
	ErrNotYou                   = errors.New("not you")
	ErrMissingToken             = errors.New("missing token")
	ErrNoSuchGame               = errors.New("no such game")
	ErrPlayerNotFound           = errors.New("player not found")
	ErrTileNotFound             = errors.New("tile not found")
	ErrNoTile                   = errors.New("no tile provided")
	ErrNotRoundLeader           = errors.New("not round leader")
	ErrTileOccluded             = errors.New("tile occluded")
	ErrNoLine                   = errors.New("no line to play on")
	ErrTileOutOfBounds          = errors.New("tile out of bounds")
	ErrGameOver                 = errors.New("game is over")
	ErrMustPickChickenFoot      = errors.New("must pick chicken foot next to round leader")
	ErrMustDrawTile             = errors.New("must draw tile")
	ErrNoSuchPlayer             = errors.New("no such player... who are you")
	ErrNoBlockingFeet           = errors.New("you must let all players lay at least one tile on their own line")
	ErrSpacerNotStraight        = errors.New("spacer not straight")
	ErrWrongLengthSpacer        = errors.New("spacer must span 6 squares")
	ErrSpacerNotStartedOnLine   = errors.New("spacer not started on a line")
	ErrSpacerNoChickenFoot      = errors.New("cannot lay spacer while chicken-footed")
	ErrYouAreFooted             = errors.New("you can only play on your own line when chicken-footed")
	ErrNoURL                    = errors.New("no url provided")
	ErrNoRegisteredPlayer       = errors.New("no registered player")
	ErrPlayerAlreadyRegistered  = errors.New("player already registered")
	ErrNotYourPlayer            = errors.New("not your player")
	ErrMissingUserID            = errors.New("missing user id")
	ErrInvalidToken             = errors.New("invalid token")
	ErrMustPlayOnFoot           = errors.New("you must play on your own foot")
	ErrMustMatchPips            = errors.New("you must match the pips of the previous tile")
	ErrNotAdjacent              = errors.New("tile is not adjacent to the previous tile")
	ErrWrongSide                = errors.New("this tile could be played if reversed")
	ErrEmptyBag                 = errors.New("no tiles left in the bag")
	ErrMustBeNearRoundLeader    = errors.New("you must choose a chicken foot location adjacent to the round leader")
	ErrNoOpenAdjacent           = errors.New("you need to leave yourself at least one open square next to the foot")
	ErrLineIsNotFooted          = errors.New("the player who owns that line is not footed")
	ErrPlayerAlreadyDead        = errors.New("that line is already dead")
	ErrFreeFromSpacer           = errors.New("free lines must begin off a spacer")
	ErrPlayerNameTooLong        = errors.New("player name too long")
)
