FROM alpine

RUN apk update && apk add ca-certificates && update-ca-certificates && rm -rf /var/cache/apk/*

COPY gopath/bin/tronimoes_server /bin/tronimoes_server

ENTRYPOINT ["/bin/tronimoes_server"]
