// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.15.0
// source: tiles.proto

package tiles

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Alpha *Side `protobuf:"bytes,1,opt,name=alpha,proto3" json:"alpha,omitempty"`
	Beta  *Side `protobuf:"bytes,2,opt,name=beta,proto3" json:"beta,omitempty"`
}

func (x *Tile) Reset() {
	*x = Tile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tiles_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tile) ProtoMessage() {}

func (x *Tile) ProtoReflect() protoreflect.Message {
	mi := &file_tiles_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tile.ProtoReflect.Descriptor instead.
func (*Tile) Descriptor() ([]byte, []int) {
	return file_tiles_proto_rawDescGZIP(), []int{0}
}

func (x *Tile) GetAlpha() *Side {
	if x != nil {
		return x.Alpha
	}
	return nil
}

func (x *Tile) GetBeta() *Side {
	if x != nil {
		return x.Beta
	}
	return nil
}

type Side struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pips int32 `protobuf:"varint,1,opt,name=pips,proto3" json:"pips,omitempty"`
}

func (x *Side) Reset() {
	*x = Side{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tiles_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Side) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Side) ProtoMessage() {}

func (x *Side) ProtoReflect() protoreflect.Message {
	mi := &file_tiles_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Side.ProtoReflect.Descriptor instead.
func (*Side) Descriptor() ([]byte, []int) {
	return file_tiles_proto_rawDescGZIP(), []int{1}
}

func (x *Side) GetPips() int32 {
	if x != nil {
		return x.Pips
	}
	return 0
}

type Coord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Coord) Reset() {
	*x = Coord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tiles_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Coord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coord) ProtoMessage() {}

func (x *Coord) ProtoReflect() protoreflect.Message {
	mi := &file_tiles_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coord.ProtoReflect.Descriptor instead.
func (*Coord) Descriptor() ([]byte, []int) {
	return file_tiles_proto_rawDescGZIP(), []int{2}
}

func (x *Coord) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Coord) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Placement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tile  *Tile  `protobuf:"bytes,1,opt,name=tile,proto3" json:"tile,omitempty"`
	Alpha *Coord `protobuf:"bytes,2,opt,name=alpha,proto3" json:"alpha,omitempty"`
	Beta  *Coord `protobuf:"bytes,3,opt,name=beta,proto3" json:"beta,omitempty"`
}

func (x *Placement) Reset() {
	*x = Placement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tiles_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Placement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Placement) ProtoMessage() {}

func (x *Placement) ProtoReflect() protoreflect.Message {
	mi := &file_tiles_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Placement.ProtoReflect.Descriptor instead.
func (*Placement) Descriptor() ([]byte, []int) {
	return file_tiles_proto_rawDescGZIP(), []int{3}
}

func (x *Placement) GetTile() *Tile {
	if x != nil {
		return x.Tile
	}
	return nil
}

func (x *Placement) GetAlpha() *Coord {
	if x != nil {
		return x.Alpha
	}
	return nil
}

func (x *Placement) GetBeta() *Coord {
	if x != nil {
		return x.Beta
	}
	return nil
}

type Line struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Placements []*Placement `protobuf:"bytes,1,rep,name=placements,proto3" json:"placements,omitempty"`
	Owner      string       `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (x *Line) Reset() {
	*x = Line{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tiles_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Line) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Line) ProtoMessage() {}

func (x *Line) ProtoReflect() protoreflect.Message {
	mi := &file_tiles_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Line.ProtoReflect.Descriptor instead.
func (*Line) Descriptor() ([]byte, []int) {
	return file_tiles_proto_rawDescGZIP(), []int{4}
}

func (x *Line) GetPlacements() []*Placement {
	if x != nil {
		return x.Placements
	}
	return nil
}

func (x *Line) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

type Board struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoundLeader *Placement `protobuf:"bytes,1,opt,name=round_leader,json=roundLeader,proto3" json:"round_leader,omitempty"`
	Lines       []*Line    `protobuf:"bytes,2,rep,name=lines,proto3" json:"lines,omitempty"`
}

func (x *Board) Reset() {
	*x = Board{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tiles_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Board) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Board) ProtoMessage() {}

func (x *Board) ProtoReflect() protoreflect.Message {
	mi := &file_tiles_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Board.ProtoReflect.Descriptor instead.
func (*Board) Descriptor() ([]byte, []int) {
	return file_tiles_proto_rawDescGZIP(), []int{5}
}

func (x *Board) GetRoundLeader() *Placement {
	if x != nil {
		return x.RoundLeader
	}
	return nil
}

func (x *Board) GetLines() []*Line {
	if x != nil {
		return x.Lines
	}
	return nil
}

var File_tiles_proto protoreflect.FileDescriptor

var file_tiles_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x74, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1b, 0x73,
	0x6b, 0x65, 0x6c, 0x74, 0x65, 0x72, 0x6a, 0x6f, 0x68, 0x6e, 0x2e, 0x74, 0x72, 0x6f, 0x6e, 0x69,
	0x6d, 0x6f, 0x65, 0x73, 0x2e, 0x74, 0x69, 0x6c, 0x65, 0x73, 0x22, 0x76, 0x0a, 0x04, 0x54, 0x69,
	0x6c, 0x65, 0x12, 0x37, 0x0a, 0x05, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x73, 0x6b, 0x65, 0x6c, 0x74, 0x65, 0x72, 0x6a, 0x6f, 0x68, 0x6e, 0x2e,
	0x74, 0x72, 0x6f, 0x6e, 0x69, 0x6d, 0x6f, 0x65, 0x73, 0x2e, 0x74, 0x69, 0x6c, 0x65, 0x73, 0x2e,
	0x53, 0x69, 0x64, 0x65, 0x52, 0x05, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x12, 0x35, 0x0a, 0x04, 0x62,
	0x65, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x73, 0x6b, 0x65, 0x6c,
	0x74, 0x65, 0x72, 0x6a, 0x6f, 0x68, 0x6e, 0x2e, 0x74, 0x72, 0x6f, 0x6e, 0x69, 0x6d, 0x6f, 0x65,
	0x73, 0x2e, 0x74, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x53, 0x69, 0x64, 0x65, 0x52, 0x04, 0x62, 0x65,
	0x74, 0x61, 0x22, 0x1a, 0x0a, 0x04, 0x53, 0x69, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x69,
	0x70, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x69, 0x70, 0x73, 0x22, 0x23,
	0x0a, 0x05, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x01, 0x79, 0x22, 0xb4, 0x01, 0x0a, 0x09, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x35, 0x0a, 0x04, 0x74, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x21, 0x2e, 0x73, 0x6b, 0x65, 0x6c, 0x74, 0x65, 0x72, 0x6a, 0x6f, 0x68, 0x6e, 0x2e, 0x74, 0x72,
	0x6f, 0x6e, 0x69, 0x6d, 0x6f, 0x65, 0x73, 0x2e, 0x74, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x54, 0x69,
	0x6c, 0x65, 0x52, 0x04, 0x74, 0x69, 0x6c, 0x65, 0x12, 0x38, 0x0a, 0x05, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x73, 0x6b, 0x65, 0x6c, 0x74, 0x65,
	0x72, 0x6a, 0x6f, 0x68, 0x6e, 0x2e, 0x74, 0x72, 0x6f, 0x6e, 0x69, 0x6d, 0x6f, 0x65, 0x73, 0x2e,
	0x74, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x52, 0x05, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x12, 0x36, 0x0a, 0x04, 0x62, 0x65, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x22, 0x2e, 0x73, 0x6b, 0x65, 0x6c, 0x74, 0x65, 0x72, 0x6a, 0x6f, 0x68, 0x6e, 0x2e, 0x74,
	0x72, 0x6f, 0x6e, 0x69, 0x6d, 0x6f, 0x65, 0x73, 0x2e, 0x74, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x43,
	0x6f, 0x6f, 0x72, 0x64, 0x52, 0x04, 0x62, 0x65, 0x74, 0x61, 0x22, 0x64, 0x0a, 0x04, 0x4c, 0x69,
	0x6e, 0x65, 0x12, 0x46, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x73, 0x6b, 0x65, 0x6c, 0x74, 0x65, 0x72,
	0x6a, 0x6f, 0x68, 0x6e, 0x2e, 0x74, 0x72, 0x6f, 0x6e, 0x69, 0x6d, 0x6f, 0x65, 0x73, 0x2e, 0x74,
	0x69, 0x6c, 0x65, 0x73, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0a,
	0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77,
	0x6e, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72,
	0x22, 0x8b, 0x01, 0x0a, 0x05, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x49, 0x0a, 0x0c, 0x72, 0x6f,
	0x75, 0x6e, 0x64, 0x5f, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x26, 0x2e, 0x73, 0x6b, 0x65, 0x6c, 0x74, 0x65, 0x72, 0x6a, 0x6f, 0x68, 0x6e, 0x2e, 0x74,
	0x72, 0x6f, 0x6e, 0x69, 0x6d, 0x6f, 0x65, 0x73, 0x2e, 0x74, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x50,
	0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0b, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x4c,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x37, 0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x73, 0x6b, 0x65, 0x6c, 0x74, 0x65, 0x72, 0x6a, 0x6f,
	0x68, 0x6e, 0x2e, 0x74, 0x72, 0x6f, 0x6e, 0x69, 0x6d, 0x6f, 0x65, 0x73, 0x2e, 0x74, 0x69, 0x6c,
	0x65, 0x73, 0x2e, 0x4c, 0x69, 0x6e, 0x65, 0x52, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x42, 0x09,
	0x5a, 0x07, 0x2e, 0x3b, 0x74, 0x69, 0x6c, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_tiles_proto_rawDescOnce sync.Once
	file_tiles_proto_rawDescData = file_tiles_proto_rawDesc
)

func file_tiles_proto_rawDescGZIP() []byte {
	file_tiles_proto_rawDescOnce.Do(func() {
		file_tiles_proto_rawDescData = protoimpl.X.CompressGZIP(file_tiles_proto_rawDescData)
	})
	return file_tiles_proto_rawDescData
}

var file_tiles_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_tiles_proto_goTypes = []interface{}{
	(*Tile)(nil),      // 0: skelterjohn.tronimoes.tiles.Tile
	(*Side)(nil),      // 1: skelterjohn.tronimoes.tiles.Side
	(*Coord)(nil),     // 2: skelterjohn.tronimoes.tiles.Coord
	(*Placement)(nil), // 3: skelterjohn.tronimoes.tiles.Placement
	(*Line)(nil),      // 4: skelterjohn.tronimoes.tiles.Line
	(*Board)(nil),     // 5: skelterjohn.tronimoes.tiles.Board
}
var file_tiles_proto_depIdxs = []int32{
	1, // 0: skelterjohn.tronimoes.tiles.Tile.alpha:type_name -> skelterjohn.tronimoes.tiles.Side
	1, // 1: skelterjohn.tronimoes.tiles.Tile.beta:type_name -> skelterjohn.tronimoes.tiles.Side
	0, // 2: skelterjohn.tronimoes.tiles.Placement.tile:type_name -> skelterjohn.tronimoes.tiles.Tile
	2, // 3: skelterjohn.tronimoes.tiles.Placement.alpha:type_name -> skelterjohn.tronimoes.tiles.Coord
	2, // 4: skelterjohn.tronimoes.tiles.Placement.beta:type_name -> skelterjohn.tronimoes.tiles.Coord
	3, // 5: skelterjohn.tronimoes.tiles.Line.placements:type_name -> skelterjohn.tronimoes.tiles.Placement
	3, // 6: skelterjohn.tronimoes.tiles.Board.round_leader:type_name -> skelterjohn.tronimoes.tiles.Placement
	4, // 7: skelterjohn.tronimoes.tiles.Board.lines:type_name -> skelterjohn.tronimoes.tiles.Line
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_tiles_proto_init() }
func file_tiles_proto_init() {
	if File_tiles_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tiles_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tiles_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Side); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tiles_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Coord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tiles_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Placement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tiles_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Line); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tiles_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Board); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tiles_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tiles_proto_goTypes,
		DependencyIndexes: file_tiles_proto_depIdxs,
		MessageInfos:      file_tiles_proto_msgTypes,
	}.Build()
	File_tiles_proto = out.File
	file_tiles_proto_rawDesc = nil
	file_tiles_proto_goTypes = nil
	file_tiles_proto_depIdxs = nil
}
