players:
  - name: Alpha
    max_inference_time_ms: 1000
    max_simulation_time_ms: 10000
    max_simulation_depth: 15
    value_decay: 0.9
  - name: Beta
    max_inference_time_ms: 800
    max_simulation_time_ms: 4000
    max_simulation_depth: 12
    value_decay: 0.85
  - name: Gamma
    max_inference_time_ms: 800
    max_simulation_time_ms: 10000
    max_simulation_depth: 10
    value_decay: 0.85
  - name: Kappa
    max_inference_time_ms: 800
    max_simulation_time_ms: 10000
    max_simulation_depth: 6
    value_decay: 0.85
