// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tronimoes.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Operation_Status int32

const (
	Operation_UNKNOWN Operation_Status = 0
	Operation_SUCCESS Operation_Status = 1
	Operation_FAILURE Operation_Status = 2
)

var Operation_Status_name = map[int32]string{
	0: "UNKNOWN",
	1: "SUCCESS",
	2: "FAILURE",
}

var Operation_Status_value = map[string]int32{
	"UNKNOWN": 0,
	"SUCCESS": 1,
	"FAILURE": 2,
}

func (x Operation_Status) String() string {
	return proto.EnumName(Operation_Status_name, int32(x))
}

func (Operation_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_786f716abeafd7fa, []int{3, 0}
}

type CreateGameRequest struct {
	// If discoverable is true, players can join you without knowing you.
	Discoverable bool `protobuf:"varint,1,opt,name=discoverable,proto3" json:"discoverable,omitempty"`
	// Only look for games that involve one of these players.
	Players []string `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	// If private is true, don't join a game with a player not requested.
	Private    bool  `protobuf:"varint,3,opt,name=private,proto3" json:"private,omitempty"`
	MinPlayers int32 `protobuf:"varint,4,opt,name=min_players,json=minPlayers,proto3" json:"min_players,omitempty"`
	MaxPlayers int32 `protobuf:"varint,5,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	// The name of the player attempting to create a game.
	PlayerSelf           string   `protobuf:"bytes,6,opt,name=player_self,json=playerSelf,proto3" json:"player_self,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGameRequest) Reset()         { *m = CreateGameRequest{} }
func (m *CreateGameRequest) String() string { return proto.CompactTextString(m) }
func (*CreateGameRequest) ProtoMessage()    {}
func (*CreateGameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_786f716abeafd7fa, []int{0}
}

func (m *CreateGameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGameRequest.Unmarshal(m, b)
}
func (m *CreateGameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGameRequest.Marshal(b, m, deterministic)
}
func (m *CreateGameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGameRequest.Merge(m, src)
}
func (m *CreateGameRequest) XXX_Size() int {
	return xxx_messageInfo_CreateGameRequest.Size(m)
}
func (m *CreateGameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGameRequest proto.InternalMessageInfo

func (m *CreateGameRequest) GetDiscoverable() bool {
	if m != nil {
		return m.Discoverable
	}
	return false
}

func (m *CreateGameRequest) GetPlayers() []string {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *CreateGameRequest) GetPrivate() bool {
	if m != nil {
		return m.Private
	}
	return false
}

func (m *CreateGameRequest) GetMinPlayers() int32 {
	if m != nil {
		return m.MinPlayers
	}
	return 0
}

func (m *CreateGameRequest) GetMaxPlayers() int32 {
	if m != nil {
		return m.MaxPlayers
	}
	return 0
}

func (m *CreateGameRequest) GetPlayerSelf() string {
	if m != nil {
		return m.PlayerSelf
	}
	return ""
}

type JoinResponse struct {
	Operation            *Operation `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *JoinResponse) Reset()         { *m = JoinResponse{} }
func (m *JoinResponse) String() string { return proto.CompactTextString(m) }
func (*JoinResponse) ProtoMessage()    {}
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_786f716abeafd7fa, []int{1}
}

func (m *JoinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinResponse.Unmarshal(m, b)
}
func (m *JoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinResponse.Marshal(b, m, deterministic)
}
func (m *JoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinResponse.Merge(m, src)
}
func (m *JoinResponse) XXX_Size() int {
	return xxx_messageInfo_JoinResponse.Size(m)
}
func (m *JoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinResponse proto.InternalMessageInfo

func (m *JoinResponse) GetOperation() *Operation {
	if m != nil {
		return m.Operation
	}
	return nil
}

type GetOperationRequest struct {
	OperationId          string   `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOperationRequest) Reset()         { *m = GetOperationRequest{} }
func (m *GetOperationRequest) String() string { return proto.CompactTextString(m) }
func (*GetOperationRequest) ProtoMessage()    {}
func (*GetOperationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_786f716abeafd7fa, []int{2}
}

func (m *GetOperationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOperationRequest.Unmarshal(m, b)
}
func (m *GetOperationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOperationRequest.Marshal(b, m, deterministic)
}
func (m *GetOperationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOperationRequest.Merge(m, src)
}
func (m *GetOperationRequest) XXX_Size() int {
	return xxx_messageInfo_GetOperationRequest.Size(m)
}
func (m *GetOperationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOperationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOperationRequest proto.InternalMessageInfo

func (m *GetOperationRequest) GetOperationId() string {
	if m != nil {
		return m.OperationId
	}
	return ""
}

type Operation struct {
	OperationId          string           `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Done                 bool             `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	Payload              *any.Any         `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Status               Operation_Status `protobuf:"varint,4,opt,name=status,proto3,enum=skelterjohn.tronimoes.Operation_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Operation) Reset()         { *m = Operation{} }
func (m *Operation) String() string { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()    {}
func (*Operation) Descriptor() ([]byte, []int) {
	return fileDescriptor_786f716abeafd7fa, []int{3}
}

func (m *Operation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operation.Unmarshal(m, b)
}
func (m *Operation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operation.Marshal(b, m, deterministic)
}
func (m *Operation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operation.Merge(m, src)
}
func (m *Operation) XXX_Size() int {
	return xxx_messageInfo_Operation.Size(m)
}
func (m *Operation) XXX_DiscardUnknown() {
	xxx_messageInfo_Operation.DiscardUnknown(m)
}

var xxx_messageInfo_Operation proto.InternalMessageInfo

func (m *Operation) GetOperationId() string {
	if m != nil {
		return m.OperationId
	}
	return ""
}

func (m *Operation) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

func (m *Operation) GetPayload() *any.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Operation) GetStatus() Operation_Status {
	if m != nil {
		return m.Status
	}
	return Operation_UNKNOWN
}

type GetGameRequest struct {
	GameId               string   `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGameRequest) Reset()         { *m = GetGameRequest{} }
func (m *GetGameRequest) String() string { return proto.CompactTextString(m) }
func (*GetGameRequest) ProtoMessage()    {}
func (*GetGameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_786f716abeafd7fa, []int{4}
}

func (m *GetGameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGameRequest.Unmarshal(m, b)
}
func (m *GetGameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGameRequest.Marshal(b, m, deterministic)
}
func (m *GetGameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGameRequest.Merge(m, src)
}
func (m *GetGameRequest) XXX_Size() int {
	return xxx_messageInfo_GetGameRequest.Size(m)
}
func (m *GetGameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGameRequest proto.InternalMessageInfo

func (m *GetGameRequest) GetGameId() string {
	if m != nil {
		return m.GameId
	}
	return ""
}

type Game struct {
	GameId               string   `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Players              []string `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game) Reset()         { *m = Game{} }
func (m *Game) String() string { return proto.CompactTextString(m) }
func (*Game) ProtoMessage()    {}
func (*Game) Descriptor() ([]byte, []int) {
	return fileDescriptor_786f716abeafd7fa, []int{5}
}

func (m *Game) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game.Unmarshal(m, b)
}
func (m *Game) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game.Marshal(b, m, deterministic)
}
func (m *Game) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game.Merge(m, src)
}
func (m *Game) XXX_Size() int {
	return xxx_messageInfo_Game.Size(m)
}
func (m *Game) XXX_DiscardUnknown() {
	xxx_messageInfo_Game.DiscardUnknown(m)
}

var xxx_messageInfo_Game proto.InternalMessageInfo

func (m *Game) GetGameId() string {
	if m != nil {
		return m.GameId
	}
	return ""
}

func (m *Game) GetPlayers() []string {
	if m != nil {
		return m.Players
	}
	return nil
}

func init() {
	proto.RegisterEnum("skelterjohn.tronimoes.Operation_Status", Operation_Status_name, Operation_Status_value)
	proto.RegisterType((*CreateGameRequest)(nil), "skelterjohn.tronimoes.CreateGameRequest")
	proto.RegisterType((*JoinResponse)(nil), "skelterjohn.tronimoes.JoinResponse")
	proto.RegisterType((*GetOperationRequest)(nil), "skelterjohn.tronimoes.GetOperationRequest")
	proto.RegisterType((*Operation)(nil), "skelterjohn.tronimoes.Operation")
	proto.RegisterType((*GetGameRequest)(nil), "skelterjohn.tronimoes.GetGameRequest")
	proto.RegisterType((*Game)(nil), "skelterjohn.tronimoes.Game")
}

func init() { proto.RegisterFile("tronimoes.proto", fileDescriptor_786f716abeafd7fa) }

var fileDescriptor_786f716abeafd7fa = []byte{
	// 480 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0x71, 0x9a, 0xd8, 0x78, 0x1c, 0x95, 0xb0, 0x80, 0x30, 0xe5, 0x80, 0xb1, 0x84, 0x30,
	0x1c, 0x1c, 0x29, 0x5c, 0xe0, 0x02, 0x2a, 0x51, 0x89, 0xc2, 0x47, 0x8a, 0xd6, 0x44, 0x20, 0x84,
	0x14, 0x6d, 0xf1, 0x24, 0x18, 0xec, 0x5d, 0x63, 0x6f, 0xaa, 0xe6, 0x35, 0x78, 0x30, 0x9e, 0x82,
	0x07, 0x41, 0x5e, 0x7f, 0x24, 0x88, 0x5a, 0xed, 0xc9, 0x9e, 0x99, 0xdf, 0x7f, 0xb4, 0x33, 0xf3,
	0x87, 0x6b, 0x32, 0x13, 0x3c, 0x4a, 0x04, 0xe6, 0x7e, 0x9a, 0x09, 0x29, 0xc8, 0xad, 0xfc, 0x07,
	0xc6, 0x12, 0xb3, 0xef, 0xe2, 0x1b, 0xf7, 0x9b, 0xe2, 0xc1, 0x9d, 0x95, 0x10, 0xab, 0x18, 0x87,
	0x0a, 0x3a, 0x59, 0x2f, 0x87, 0x8c, 0x6f, 0x4a, 0x85, 0xfb, 0x5b, 0x83, 0xeb, 0xe3, 0x0c, 0x99,
	0xc4, 0x09, 0x4b, 0x90, 0xe2, 0xcf, 0x35, 0xe6, 0x92, 0xb8, 0xd0, 0x0f, 0xa3, 0xfc, 0xab, 0x38,
	0xc5, 0x8c, 0x9d, 0xc4, 0x68, 0x6b, 0x8e, 0xe6, 0x5d, 0xa5, 0xff, 0xe4, 0x88, 0x0d, 0x46, 0x1a,
	0xb3, 0x0d, 0x66, 0xb9, 0xdd, 0x71, 0xf6, 0x3c, 0x93, 0xd6, 0xa1, 0xaa, 0x64, 0xd1, 0x29, 0x93,
	0x68, 0xef, 0x29, 0x61, 0x1d, 0x92, 0x7b, 0x60, 0x25, 0x11, 0x5f, 0xd4, 0xba, 0xae, 0xa3, 0x79,
	0x3d, 0x0a, 0x49, 0xc4, 0xdf, 0x57, 0xd2, 0x02, 0x60, 0x67, 0x0d, 0xd0, 0xab, 0x00, 0x76, 0xb6,
	0x03, 0x94, 0xc5, 0x45, 0x8e, 0xf1, 0xd2, 0xd6, 0x1d, 0xcd, 0x33, 0x29, 0x94, 0xa9, 0x00, 0xe3,
	0xa5, 0x3b, 0x83, 0xfe, 0x6b, 0x11, 0x71, 0x8a, 0x79, 0x2a, 0x78, 0x8e, 0xe4, 0x39, 0x98, 0x22,
	0xc5, 0x8c, 0xc9, 0x48, 0x70, 0x35, 0x87, 0x35, 0x72, 0xfc, 0x73, 0xd7, 0xe4, 0x1f, 0xd7, 0x1c,
	0xdd, 0x4a, 0xdc, 0xa7, 0x70, 0x63, 0x82, 0x72, 0x5b, 0xaa, 0x36, 0x74, 0x1f, 0xfa, 0x0d, 0xb3,
	0x88, 0x42, 0xd5, 0xd9, 0xa4, 0x56, 0x93, 0x9b, 0x86, 0xee, 0x1f, 0x0d, 0xcc, 0x46, 0x77, 0x09,
	0x01, 0x21, 0xd0, 0x0d, 0x05, 0x47, 0xbb, 0xa3, 0x96, 0xa6, 0xfe, 0x89, 0x0f, 0x46, 0xca, 0x36,
	0xb1, 0x60, 0xa1, 0xda, 0xa5, 0x35, 0xba, 0xe9, 0x97, 0xc7, 0xf4, 0xeb, 0x63, 0xfa, 0x87, 0x7c,
	0x43, 0x6b, 0x88, 0xbc, 0x00, 0x3d, 0x97, 0x4c, 0xae, 0xcb, 0xe5, 0xee, 0x8f, 0x1e, 0x5e, 0x34,
	0xab, 0x1f, 0x28, 0x9c, 0x56, 0x32, 0x77, 0x08, 0x7a, 0x99, 0x21, 0x16, 0x18, 0xf3, 0xd9, 0x9b,
	0xd9, 0xf1, 0xc7, 0xd9, 0xe0, 0x4a, 0x11, 0x04, 0xf3, 0xf1, 0xf8, 0x28, 0x08, 0x06, 0x5a, 0x11,
	0xbc, 0x3a, 0x9c, 0xbe, 0x9d, 0xd3, 0xa3, 0x41, 0xc7, 0x7d, 0x04, 0xfb, 0x13, 0x94, 0xbb, 0xee,
	0xb9, 0x0d, 0xc6, 0x8a, 0x25, 0xb8, 0x9d, 0x52, 0x2f, 0xc2, 0x69, 0xe8, 0x3e, 0x83, 0x6e, 0xc1,
	0xb5, 0x02, 0xed, 0x9e, 0x1a, 0xfd, 0xea, 0x80, 0xf9, 0xa1, 0x7e, 0x3d, 0xf9, 0x04, 0xb0, 0x35,
	0x2d, 0xf1, 0x5a, 0x66, 0xfc, 0xcf, 0xd7, 0x07, 0x17, 0x5e, 0x9e, 0x7c, 0x81, 0xfe, 0xee, 0xb9,
	0xc9, 0xe3, 0x16, 0xc5, 0x39, 0x9e, 0xb8, 0x44, 0xf7, 0x77, 0x60, 0x54, 0xbb, 0x22, 0x0f, 0xda,
	0x1b, 0xef, 0xbe, 0xf8, 0x6e, 0x1b, 0xc6, 0x12, 0x7c, 0x69, 0x7c, 0xee, 0x95, 0x2e, 0xd0, 0xd5,
	0xe7, 0xc9, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3c, 0x69, 0x81, 0xdf, 0x11, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TronimoesClient is the client API for Tronimoes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TronimoesClient interface {
	CreateGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*Operation, error)
	GetOperation(ctx context.Context, in *GetOperationRequest, opts ...grpc.CallOption) (*Operation, error)
	GetGame(ctx context.Context, in *GetGameRequest, opts ...grpc.CallOption) (*Game, error)
}

type tronimoesClient struct {
	cc grpc.ClientConnInterface
}

func NewTronimoesClient(cc grpc.ClientConnInterface) TronimoesClient {
	return &tronimoesClient{cc}
}

func (c *tronimoesClient) CreateGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*Operation, error) {
	out := new(Operation)
	err := c.cc.Invoke(ctx, "/skelterjohn.tronimoes.Tronimoes/CreateGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tronimoesClient) GetOperation(ctx context.Context, in *GetOperationRequest, opts ...grpc.CallOption) (*Operation, error) {
	out := new(Operation)
	err := c.cc.Invoke(ctx, "/skelterjohn.tronimoes.Tronimoes/GetOperation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tronimoesClient) GetGame(ctx context.Context, in *GetGameRequest, opts ...grpc.CallOption) (*Game, error) {
	out := new(Game)
	err := c.cc.Invoke(ctx, "/skelterjohn.tronimoes.Tronimoes/GetGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TronimoesServer is the server API for Tronimoes service.
type TronimoesServer interface {
	CreateGame(context.Context, *CreateGameRequest) (*Operation, error)
	GetOperation(context.Context, *GetOperationRequest) (*Operation, error)
	GetGame(context.Context, *GetGameRequest) (*Game, error)
}

// UnimplementedTronimoesServer can be embedded to have forward compatible implementations.
type UnimplementedTronimoesServer struct {
}

func (*UnimplementedTronimoesServer) CreateGame(ctx context.Context, req *CreateGameRequest) (*Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGame not implemented")
}
func (*UnimplementedTronimoesServer) GetOperation(ctx context.Context, req *GetOperationRequest) (*Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOperation not implemented")
}
func (*UnimplementedTronimoesServer) GetGame(ctx context.Context, req *GetGameRequest) (*Game, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGame not implemented")
}

func RegisterTronimoesServer(s *grpc.Server, srv TronimoesServer) {
	s.RegisterService(&_Tronimoes_serviceDesc, srv)
}

func _Tronimoes_CreateGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TronimoesServer).CreateGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/skelterjohn.tronimoes.Tronimoes/CreateGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TronimoesServer).CreateGame(ctx, req.(*CreateGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tronimoes_GetOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TronimoesServer).GetOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/skelterjohn.tronimoes.Tronimoes/GetOperation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TronimoesServer).GetOperation(ctx, req.(*GetOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tronimoes_GetGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TronimoesServer).GetGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/skelterjohn.tronimoes.Tronimoes/GetGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TronimoesServer).GetGame(ctx, req.(*GetGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Tronimoes_serviceDesc = grpc.ServiceDesc{
	ServiceName: "skelterjohn.tronimoes.Tronimoes",
	HandlerType: (*TronimoesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGame",
			Handler:    _Tronimoes_CreateGame_Handler,
		},
		{
			MethodName: "GetOperation",
			Handler:    _Tronimoes_GetOperation_Handler,
		},
		{
			MethodName: "GetGame",
			Handler:    _Tronimoes_GetGame_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tronimoes.proto",
}
